name: Laravel

on:
  push:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Install PHP
      run: sudo apt install php -y && composer
    - name: Check Php Version
      run: php -v
    - name: Install Composer
      run: sudo apt install composer
    - name: Check Composer Version
      run: composer -V
    - name: Install sqlite
      run: sudo apt install sqlite3
    - name: Check Sqlite
      run: sqlite3 --version