name: Laravel

on:
  push:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Install composer and PHP
      run: sudo apt install php -y && composer
    - name: Check Php Version
      run: php -v